### ISSUE TITLE
Exception when upgrading from 0.4.40 to 0.5.3 - "java.lang.NoClassDefFoundError: datalevin/util$graal_QMARK_"

### ISSUE THREAD

**Issue by mokr** [juji-io/datalevin#62]
Hi! After just replacing `[datalevin "0.4.40"]` with `[datalevin "0.5.3"]` in `project.clj` I got the following (truncated) exception:
```
Exception in thread "main" Syntax error compiling at (plug_sso/db/entities/access.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7652)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	<truncated>
	at clojure.lang.RT.doInit(RT.java:486)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.main.main(main.java:38)
Caused by: java.lang.NoClassDefFoundError: datalevin/util$graal_QMARK_
	at datalevin.util__init.load(Unknown Source)
	at datalevin.util__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2212)
	<truncated>
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	... 118 more
Caused by: java.lang.ClassNotFoundException: datalevin.util$graal_QMARK_
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 177 more
```
That namespace just :require [datalevin.core :as d] and was working fine before the upgrade. I could not find any information that suggested additional steps were needed when upgrading to 0.5.x, but please enlighten me if I missed something.

BTW, digging around I noticed that Datalevin's `util.cljc` file uses reader conditonals for the utility fn `graal?` mentioned in the stack trace, but it is called without conditionals from e.g. `core.cljc`. Could that cause this issue?

**Some additional info:**
```
> sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95

> clojure --version
Clojure CLI version 1.10.3.967

> lein --version
Leiningen 2.9.6 on Java 11.0.12 OpenJDK 64-Bit Server VM

> java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
```

**Comment by mokr** [comment]
v0.5.4 solved the issue, thanks for the quick fix.
